# numpy 


Propicio para matematicas matrical

1. se llaman tensores de gfrado uno a los que son un vector horizontal o vertical de una dimensión

2. Tensores de grado 2, doble dimencion Alto y ancho

3. Tensores de grado 3, tres dimensiones

In [1]:
import numpy as np


## Creacion de un arreglo

### Vectores 1 dimension

In [2]:
a = np.array([5, 27, 2])
b = np.array([6.2, 5.3, 8.4, 9.2])

print(a)
print(b)

#Los tipos son array ndimensionales
print(type(a))
print(type(b))



[ 5 27  2]
[6.2 5.3 8.4 9.2]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Vector de 2 dimensiones


In [3]:
D = np.array([[2, 3, 6], [4, 3, 6], [4.5, 2.3, 8.2]])

print(D)

[[2.  3.  6. ]
 [4.  3.  6. ]
 [4.5 2.3 8.2]]


## Atributos de un Arreglo

### Atributo _dtype_
El arreglo entero es de 64 bits es decir que cada celda esta almacenada en memoria con 64 bits de tamaño

In [4]:
D.dtype

dtype('float64')

### Atributo _ndim_

Indica las dimenciones del arreglo


In [5]:
# El arreglo D es de dos dimensiones

D.ndim

2

### Atributo _shape_

Devuelve una tupla que Indica el tamaño arreglo

In [6]:
D.shape

(3, 3)

### Atributo _size_

Devuelve el valor total de elemntos en una matriz ejemplo 2*3=6

In [7]:
D.size

9

# Funciones para la creacion de ARREGLOS

## _Zeros_, _ones_, _full_

In [8]:
a = np.zeros((4, 2, 3))
a

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
b = np.ones((4, 2, 3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
c = np.full((4, 2, 3), 7)
c

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])

In [14]:
D = np.ones(7, dtype=float)
print(D)

print(f"Dimensiones del arreglo {D.ndim}")  
print(f"Tipo de datos arreglo {D.dtype}") 

[1. 1. 1. 1. 1. 1. 1.]
Dimensiones del arreglo 1
Tipo de datos arreglo float64


## Creacion de Areglos 

### arange + reshape

In [17]:
A = np.arange(10)
print(A)

C = np.arange(-10, 10)
print(C)

B = np.arange(3, 10, 2)
print(B)

[0 1 2 3 4 5 6 7 8 9]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9]
[3 5 7 9]


reshape permite  convertir el arreglo en 2 dimensiones o mas dimensiones segun


In [18]:
D = np.arange(2, 101, 2)
F = D.reshape((5, 10))

print(D)
print(F)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


Mismo resultado anterior pero en una sola linea de codigo

In [19]:
G = np.arange(2, 101, 2).reshape((5, 10))
print(G)

[[  2   4   6   8  10  12  14  16  18  20]
 [ 22  24  26  28  30  32  34  36  38  40]
 [ 42  44  46  48  50  52  54  56  58  60]
 [ 62  64  66  68  70  72  74  76  78  80]
 [ 82  84  86  88  90  92  94  96  98 100]]


### Funcion _linespace_

Crea un var dentro de un rango, pero lo divide en las partes que uno desee. donde el primer valor sera el minimo del rango y el ultimop valor el ultimo designado.

In [22]:
H = np.linspace(0, 10, 100)
print(H)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [1]:
#mEJORARLO CON RESHAPE

I = H.reshape((20, 5))
print(I)

NameError: name 'H' is not defined

# Listas vs numpy

Comparaciones

In [5]:
import numpy as np
import timeit

#Creearemos arreglos de 10, 100, 1000, 10000, 10000000
#Calculamos el tiempo de cada uno

N = [10, 10**2, 10**3, 10**4, 10**5, 10**6]

for i in N:
    #Generar los arreglos python y numpy
    x_python = list(range(i))
    x_numpy = np.arange(i)

    # Calcular el tiempo de computo pronmedio para python y alamacenarlo
    t_python = timeit.timeit("sum(x_python)", "from __main__ import x_python", number=1000)/1000

    # Calcular el tiempo de computo pronmedio para python y alamacenarlo
    t_numpy = timeit.timeit("x_numpy.sum()", "from __main__ import x_numpy", number=1000)/1000


    #Imprimir informacion
    print("-" * 50)

    print(f"N = {i}:")
    print(f"    Tiempo de computo promedio en python: {t_python} segundos")
    print(f"    Tiempo de computo promedio en Numpy: {t_numpy} segundos")
    print(f"   Numpy es {t_python/t_numpy:.1f} veces más rápido")




--------------------------------------------------
N = 10:
    Tiempo de computo promedio en python: 6.719999964843737e-08 segundos
    Tiempo de computo promedio en Numpy: 1.3823999997839565e-06 segundos
   Numpy es 0.0 veces más rápido
--------------------------------------------------
N = 100:
    Tiempo de computo promedio en python: 4.013000002487388e-07 segundos
    Tiempo de computo promedio en Numpy: 1.0912000002463174e-06 segundos
   Numpy es 0.4 veces más rápido
--------------------------------------------------
N = 1000:
    Tiempo de computo promedio en python: 2.920700000231591e-06 segundos
    Tiempo de computo promedio en Numpy: 1.9300999997540203e-06 segundos
   Numpy es 1.5 veces más rápido
--------------------------------------------------
N = 10000:
    Tiempo de computo promedio en python: 2.9641500000252562e-05 segundos
    Tiempo de computo promedio en Numpy: 2.589499999885447e-06 segundos
   Numpy es 11.4 veces más rápido
-----------------------------------------

# Operadores de Arreglos

Los operadores de numpyh permiten realizar operaciones sencillas sobre *cada uno de los elementos de un arreglos*

#### Operadores principales

##### Operaciones aritmeticas con escalares

Son operaciones como suma, resta, multipliucacion y expónenciacion, para realizar opercacxiones entre un areglo y un escalar

In [7]:
import numpy as np

arreglo = np.arange(5, 15)
print(arreglo)

[ 5  6  7  8  9 10 11 12 13 14]


In [8]:
# 1. Sumar o restare la misma cantidad a cada elemento del arreglo
print(arreglo + 2)

[ 7  8  9 10 11 12 13 14 15 16]


In [9]:
# 2. Tambien se puede usar el modificador += pero en este caso la variable original resulta afectada
arreglo += 2
print(arreglo)

[ 7  8  9 10 11 12 13 14 15 16]


In [11]:
# 3. Multiplicacion de cada elemento 

0.5 * arreglo



array([3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ])

In [19]:
# 4. Exponenciacion de cada elemento 

arreglo ** 0.5 






array([2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ])

## Operaciones aritmetica entre arreglos

Este tipo de operaciones obliga a que las dimensiones de los vectores tengan el mismo tamaño



In [21]:
areglo_1 = np.linspace(3, 5, 10)
areglo_2 = np.linspace(7, 9, 10)
areglo_3 = np.linspace(10, 15, 12)

print(areglo_1, areglo_2, areglo_3)

[3.         3.22222222 3.44444444 3.66666667 3.88888889 4.11111111
 4.33333333 4.55555556 4.77777778 5.        ] [7.         7.22222222 7.44444444 7.66666667 7.88888889 8.11111111
 8.33333333 8.55555556 8.77777778 9.        ] [10.         10.45454545 10.90909091 11.36363636 11.81818182 12.27272727
 12.72727273 13.18181818 13.63636364 14.09090909 14.54545455 15.        ]


In [23]:
# Podemnos multiplicar elemento a elemento los areglos 1 y 2
# generando un nuevo areglo de 10 elementos

areglo_1*areglo_2


array([21.        , 23.27160494, 25.64197531, 28.11111111, 30.67901235,
       33.34567901, 36.11111111, 38.97530864, 41.9382716 , 45.        ])

In [25]:
#Pero no podemos multiplicar los arglos 1 y 3 por ejemplo

areglo_1 * areglo_3

ValueError: operands could not be broadcast together with shapes (10,) (12,) 

In [27]:
# La multiplicacion se puiede estender a matirces siempre y cuendo guarden la misma dimensionalidad 

matriz_1 = areglo_1.reshape(5,2) 
matriz_2 = areglo_2.reshape(5,2)

matriz_multipli = matriz_1*matriz_2
print(matriz_multipli)

print(f"Tamaño matriz resultante: {matriz_multipli.shape}")

[[21.         23.27160494]
 [25.64197531 28.11111111]
 [30.67901235 33.34567901]
 [36.11111111 38.97530864]
 [41.9382716  45.        ]]
Tamaño matriz resultante: (5, 2)


In [29]:
matriz_suma=matriz_1 + matriz_2
print(f"Matriz 2 es: {matriz_suma}")

Matriz 2 es: [[10.         10.44444444]
 [10.88888889 11.33333333]
 [11.77777778 12.22222222]
 [12.66666667 13.11111111]
 [13.55555556 14.        ]]


## Operaciones logicas

Se pueden aplicar operadores de c omparacion para cada elemento  a elemento ( en el caso de comparar dos arreglos):


In [31]:
# comparar cada elementos de un arreglo con un escalar
areglo = np.linspace(5, 20, 20) 
print(areglo)


[ 5.          5.78947368  6.57894737  7.36842105  8.15789474  8.94736842
  9.73684211 10.52631579 11.31578947 12.10526316 12.89473684 13.68421053
 14.47368421 15.26315789 16.05263158 16.84210526 17.63157895 18.42105263
 19.21052632 20.        ]


In [33]:
# determinar que elementos son mayores o iguales  que 25: el resultado es un 
# arreglos del mismo tamaño original  pero sus elememntos serán variables 
# booleanas (True, False)


areglo >= 10



array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [37]:
#Comparaciones entre arreglos

areglo_1 < areglo_2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

# METODOS DE UN ARREGLO

Al ser un objeto un ndarray tiene metodos

In [1]:
import numpy as np

#Creemos dos arreglos un vector y una matriz
vector = np.arange(5,20) #Vector de 14 elementos
matriz = np.linspace(1, 10, 20).reshape((5, 4))

print(vector)
print(matriz)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


In [2]:
# se puede acceder a los metodos usando . + TAB
matriz

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

## Metodos _max, min, argmax, argmin_

indican:

1. max y min: los vcalores maximo y minimo del arreglo
2. argmax y argmin: las posiciones o indices del arreglo de esos valores máximo y minimo

In [3]:
valor_maximo = vector.max()
valor_minimo = vector.min()

print(f"Matriz: \n {vector}")
print(f"Valor Maximo: {valor_maximo}")
print(f"Valor Minimo: {valor_minimo}")

Matriz: 
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Valor Maximo: 19
Valor Minimo: 5


In [4]:
valor_maximo_matriz = matriz.max()
valor_minimo_matriz = matriz.min()

print(f"Matriz: \n {matriz}")
print(f"Valor Maximo: {valor_maximo_matriz}")
print(f"Valor Minimo: {valor_minimo_matriz}")

Matriz: 
 [[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]
Valor Maximo: 10.0
Valor Minimo: 1.0


In [5]:
#Si se quiere buscar por filas o por columnas en una matriz ese maximo o minimo

matriz_max_filas = matriz.max(axis=1)
matriz_min_filas = matriz.min(axis=1)

print(f"Matriz: \n {matriz}")
print(f"Valor Maximo: {matriz_max_filas}")
print(f"Valor Minimo: {matriz_min_filas}")


Matriz: 
 [[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]
Valor Maximo: [ 2.42105263  4.31578947  6.21052632  8.10526316 10.        ]
Valor Minimo: [1.         2.89473684 4.78947368 6.68421053 8.57894737]


In [7]:
#Si se quiere buscar por filas o por columnas en una matriz ese maximo o minimo

matriz_max_cols = matriz.max(axis=0)
matriz_min_cols = matriz.min(axis=0)

print(f"Matriz: \n {matriz}")
print(f"Valor Maximo: {matriz_max_cols}")
print(f"Valor Minimo: {matriz_min_cols}")


Matriz: 
 [[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]
Valor Maximo: [ 8.57894737  9.05263158  9.52631579 10.        ]
Valor Minimo: [1.         1.47368421 1.94736842 2.42105263]


In [8]:
# Argmax y argmin ´para las posiciones absolutas

indice_valor_max = vector.argmax()
indice_valor_min = vector.argmin()

print(f"Matriz: \n {vector}")
print(f"Valor Maximo: {indice_valor_max}")
print(f"Valor Minimo: {indice_valor_min}")



Matriz: 
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Valor Maximo: 14
Valor Minimo: 0


In [9]:
# argmax y argmin en una matriz pero devulve un indice lineal

m_pos_max_matriz = matriz.argmax()
m_pos_min_matriz = matriz.argmin()

print(f"Matriz: \n {matriz}")
print(f"Valor Maximo: {m_pos_max_matriz}")
print(f"Valor Minimo: {m_pos_min_matriz}")


Matriz: 
 [[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]
Valor Maximo: 19
Valor Minimo: 0
