# numpy 


Propicio para matematicas matrical

1. se llaman tensores de gfrado uno a los que son un vector horizontal o vertical de una dimensión

2. Tensores de grado 2, doble dimencion Alto y ancho

3. Tensores de grado 3, tres dimensiones

In [1]:
import numpy as np


## Creacion de un arreglo

### Vectores 1 dimension

In [2]:
a = np.array([5, 27, 2])
b = np.array([6.2, 5.3, 8.4, 9.2])

print(a)
print(b)

#Los tipos son array ndimensionales
print(type(a))
print(type(b))



[ 5 27  2]
[6.2 5.3 8.4 9.2]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### Vector de 2 dimensiones


In [6]:
D = np.array([[2, 3, 6], [4, 3, 6], [4.5, 2.3, 8.2]])

print(D)

[[2.  3.  6. ]
 [4.  3.  6. ]
 [4.5 2.3 8.2]]


## Atributos de un Arreglo

### Atributo _dtype_
El arreglo entero es de 64 bits es decir que cada celda esta almacenada en memoria con 64 bits de tamaño

In [7]:
D.dtype

dtype('float64')

### Atributo _ndim_

Indica las dimenciones del arreglo


In [8]:
# El arreglo D es de dos dimensiones

D.ndim

2

### Atributo _shape_

Devuelve una tupla que Indica el tamaño arreglo

In [9]:
D.shape

(3, 3)

### Atributo _size_

Devuelve el valor total de elemntos en una matriz ejemplo 2*3=6

In [11]:
D.size

9

# Funciones para la creacion de ARREGLOS

## _Zeros_, _ones_, _full_

In [13]:
a = np.zeros((4, 2, 3))
a

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
b = np.ones((4, 2, 3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [18]:
c = np.full((4, 2, 3), 7)
c

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])